apiVersion: v1
kind: Service
metadata:
  name: svc-tweet-api
  namespace: kwetter
  labels:
    app: tweet-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: grpc
      port: 10041
      protocol: TCP
      targetPort: 10041
  selector:
    app: tweet-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-api
  namespace: kwetter
spec:
  selector:
    matchLabels:
      app: tweet-api
  replicas: 1
  template:
    metadata:
      labels:
        app: tweet-api
    spec:
      containers:
        - name: tweet-api
          image: luukvdm/kwetter-tweet-api
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "k8s"
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:80"
            - name: Identity__authority
              value: http://ids.kwetter.test
            - name: ApplicationDb__UseInMemoryDatabase
              value: "false"
            - name: ConnectionStrings__DefaultConnection
              value: "Server=svc-tweet-db;Port=5432;Database=tweet_db;Username=admin;Password=@Welkom1;"
            - name: EventBus__HostName
              valueFrom:
                configMapKeyRef:
                  name: shared-settings
                  key: eventbus_hostname
            - name: Urls__ApiGateway
              valueFrom:
                configMapKeyRef:
                  name: shared-settings
                  key: urls_apigateway
            - name: Urls__WebSpaAggregator
              valueFrom:
                configMapKeyRef:
                  name: shared-settings
                  key: urls_webspa_aggregator
            - name: Urls__WebSpaClient
              valueFrom:
                configMapKeyRef:
                  name: shared-settings
                  key: urls_webspa_client
            - name: Urls__IdentityServerApi
              valueFrom:
                configMapKeyRef:
                  name: shared-settings
                  key: urls_ids_api
            - name: Urls__IdentityServerGrpc
              valueFrom:
                configMapKeyRef:
                  name: shared-settings
                  key: urls_ids_grpc
            - name: Urls__TweetApi
              valueFrom:
                configMapKeyRef:
                  name: shared-settings
                  key: urls_tweet_api
            - name: Urls__TweetGrpc
              valueFrom:
                configMapKeyRef:
                  name: shared-settings
                  key: urls_tweet_grpc
            - name: Urls__Hub
              valueFrom:
                configMapKeyRef:
                  name: shared-settings
                  key: urls_hub
            - name: Urls__UserRelationsApi
              valueFrom:
                configMapKeyRef:
                  name: shared-settings
                  key: urls_userrelations_api
            - name: Urls__UserRelationsGrpc
              valueFrom:
                configMapKeyRef:
                  name: shared-settings
                  key: urls_userrelations_grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-db
  namespace: kwetter
spec:
  selector:
    matchLabels:
      app: tweet-db
  replicas: 1
  template:
    metadata:
      labels:
        app: tweet-db
    spec:
      containers:
        - name: tweet-db
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "root"
            - name: POSTGRES_PASSWORD
              value: "@Welkom1"
            - name: APP_DB_USER
              value: "admin"
            - name: APP_DB_PASS
              value: "@Welkom1"
            - name: APP_DB_NAME
              value: "tweet_db"
          volumeMounts:
            - name: sqlscript
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: sqlscript
          configMap:
            name: pg-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: svc-tweet-db
  namespace: kwetter
  labels:
    app: tweet-db
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: tweet-db
