version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=@Welkom1

  main-gateway:
    image: ${REGISTRY:-luukvdm}/kwetter-main-gateway:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGateways/MainGateway/Dockerfile
    depends_on:
      - webspa-agg
      - identity-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80

  webspa-agg:
    image: ${REGISTRY:-luukvdm}/kwetter-webspa-agg:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGateways/WebSpa.Aggregator/Dockerfile
    depends_on:
      - identity-api
      - tweet-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Identity__authority=http://identity-api

  identity-api:
    image: ${REGISTRY:-luukvdm}/kwetter-identity-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Identity/Identity.Api/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - URL_BASE=http://localhost:5001
      - Urls__WebSpaClient=http://localhost:8080

  tweet-api:
    image: ${REGISTRY:-luukvdm}/kwetter-tweet-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Tweet/Api/Tweet.Api/Dockerfile
    depends_on:
      - rabbitmq
      - tweet-hub
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - UseInMemoryDatabase=true
      - EventBus__Username=admin
      - EventBus__Password=@Welkom1
      - EventBus__HostName=rabbitmq
      - Identity__authority=http://identity-api

  tweet-hub:
    image: ${REGISTRY:-luukvdm}/kwetter-tweet-hub:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Tweet/Tweet.Hub/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBus__Username=admin
      - EventBus__Password=@Welkom1
      - EventBus__HostName=rabbitmq
      - Identity__authority=http://identity-api

  webspa:
    image: ${REGISTRY:-luukvdm}/kwetter-webspa:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: WebSpa/Dockerfile
    depends_on:
      - webspa-agg
      - main-gateway

