version: '3.4'

services:
  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=@Welkom1
    ports:
      - 5672:5672
      - 15672:15672

  main-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
  
  webspa-agg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Identity__authority=http://identity-api

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - URL_BASE=http://localhost:5001
      - Urls__WebSpaClient=http://localhost:8080

  tweet-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Identity__authority=http://identity-api

  userrelations-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Identity__authority=http://identity-api

  hub:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Identity__authority=http://identity-api

