name: webspa-agg

on:
  push:
    branches: [ main ]
    paths:
      - src/BuildingBlocks/**
      - src/ApiGateways/WebSpa.Aggregator/**
      - src/Services/Tweet/Tweet.GrpcContracts/**
      - src/Services/Identity/Identity.GrpcContracts/**
      - .github/workflows/webspa-agg.yml
  pull_request:
    branches: [ main ]
    paths:
      - src/BuildingBlocks/**
      - src/ApiGateways/WebSpa.Aggregator/**
      - src/Services/Tweet/Tweet.GrpcContracts/**
      - src/Services/Identity/Identity.GrpcContracts/**
      - .github/workflows/webspa-agg.yml

  workflow_dispatch:
  
env:
  SERVICE: webspa-agg
  DOTNET_VERSION: 5.0.x

jobs:
  BuildForPR:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@main
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Compose build ${{ env.SERVICE }}
      run: sudo -E docker-compose build ${{ env.SERVICE }}
      working-directory: ./src
      shell: bash
      env:
        TAG: latest
        REGISTRY: ${{ secrets.REGISTRY_ENDPOINT }}
      
  Build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@main

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Compose build ${{ env.SERVICE }}
      run: sudo -E docker-compose build ${{ env.SERVICE }}
      working-directory: ./src
      shell: bash
      env:
        REGISTRY: ${{ secrets.REGISTRY_ENDPOINT }}

    - name: Compose push ${{ env.SERVICE }}
      run: sudo -E docker-compose push ${{ env.SERVICE }}
      working-directory: ./src
      shell: bash
      env:
        REGISTRY: ${{ secrets.REGISTRY_ENDPOINT }}
